### PR TITLE
Classroom switching is now functional

### PR DESCRIPTION
**Pull request by schaef2493**

### CODE REVIEW

**Comment by schaef2493** [comment]
Just FYI: Only the top classroom in the list seems to have students. The bottom two don't, so when you click on them... You get an empty view. I don't think this is a bad thing, though, since we probably shouldn't have a way to see a classroom with no students in the app.

**Comment by gregarious** [comment]
Ou, slide animations!

Things look good, though we do need to do something about this empty classroom situation, since choosing one from the classroom list gets you stuck with no way back without refreshing the page. 

Is there a technical reason we can't just show an empty list (maybe with a token "No students" entry) and allow the user to click the hamburger button to go back? That seems like the solution most in-line with the flow of the app and transparent about the state of the data.

If that's not possible, we'll need to throw up some kind of alert or something instead of allowing the transition to the empty classroom.

I'll merge this in for now, but we do need to address this before launching since it can get users stuck.

**Comment by schaef2493** [comment]
I assumed it would be impossible for the app, in production, to have empty classrooms. If it's a case we need to handle, I'll take care of it.

**Comment by gregarious** [comment]
Yeah, I don't really know for sure, but I imagine it's not impossible. They have said they shuffle students around classrooms pretty often.

Server-side, I've had no reason to constrain a classroom to be non-empty, so the app should be able to handle it gracefully at least.

**Pull request merged**
